### ISSUE TITLE
Reproducing results with nerf-synthetic dataset

### ISSUE THREAD

**Issue by EliaFantini** [LinjieLyu/NRTF#2]
Hello, I was trying to reproduce the results showed in the Supplemental document, where NRTF is compared to NeRFactor on hotdog and drums scenes from nerf-synthetic dataset. I'm currently struggling to understand how to convert the transform_matrix from the transforms_train.json contained in the nerf-synthetic dataset, since the matrix itself put as variable for "matrix_values" in the xml of the scene for the perspective sensor component doesn't work. Unfortunately you only provided the cameras.npz file for the hand and I can not understand how to adapt code to make it work. Thanks

**Comment by LinjieLyu** [comment]
Hello. This is because they use different camera conventions. You can use [this](https://github.com/LinjieLyu/NRTF/blob/main/blender/import_cameras_from_json.py) to import the cameras from  transforms_train.json to the nerf blender file (you probably want to render the masks there anyway). And then [export](https://github.com/LinjieLyu/NRTF/blob/main/blender/export_cameras.py) the camera matrix in our format. Take a look at the [blender folder](https://github.com/LinjieLyu/NRTF/tree/main/blender) for more references.

**Comment by EliaFantini** [comment]
Problem solved, thanks a lot for the ad-hoc script!
